"""Provider-specific parser profiles for statement extraction."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class ProviderParserProfile:
    provider: str
    detection_keywords: List[str]
    amount_labels_pdf: List[str]
    fee_labels_pdf: List[str]
    refund_labels_pdf: List[str]
    chargeback_labels_pdf: List[str]
    period_labels_pdf: List[str]
    amount_columns_tabular: List[str]
    fee_columns_tabular: List[str]
    refund_columns_tabular: List[str]
    chargeback_columns_tabular: List[str]
    date_columns_tabular: List[str]
    merchant_columns_tabular: List[str]


PROVIDER_PARSER_PROFILES: Dict[str, ProviderParserProfile] = {
    "Clover": ProviderParserProfile(
        provider="Clover",
        detection_keywords=["clover", "merchantportal.app", "fiserv"],
        amount_labels_pdf=["Transactions", "Total card transactions", "Total Amount Submitted"],
        fee_labels_pdf=["Total Fees (excluding VAT)", "Transaction Fees", "Total fees (including VAT)"],
        refund_labels_pdf=["Refunds"],
        chargeback_labels_pdf=["Chargebacks / Reversals", "Chargebacks"],
        period_labels_pdf=["Period:"],
        amount_columns_tabular=["transactions", "sales", "gross", "submitted amount"],
        fee_columns_tabular=["transaction fees", "fees", "fee amount", "commission"],
        refund_columns_tabular=["refunds", "refund amount"],
        chargeback_columns_tabular=["chargebacks", "reversals"],
        date_columns_tabular=["date", "statement date", "period end"],
        merchant_columns_tabular=["merchant id", "mid", "merchant"],
    ),
    "Stripe": ProviderParserProfile(
        provider="Stripe",
        detection_keywords=["stripe", "payout reconciliation", "balance transaction"],
        amount_labels_pdf=["Gross", "Amount", "Payments", "Charges"],
        fee_labels_pdf=["Fee", "Fees", "Stripe fee", "Application fee"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Dispute", "Chargeback"],
        period_labels_pdf=["From", "To", "Period"],
        amount_columns_tabular=["amount", "gross", "gross amount", "payments", "charge amount"],
        fee_columns_tabular=["fee", "fees", "stripe_fee", "application_fee"],
        refund_columns_tabular=["refund", "refund_amount"],
        chargeback_columns_tabular=["dispute", "chargeback"],
        date_columns_tabular=["created", "available_on", "date", "reporting_category_date"],
        merchant_columns_tabular=["merchant", "account", "connected_account"],
    ),
    "Adyen": ProviderParserProfile(
        provider="Adyen",
        detection_keywords=["adyen", "settlement details report", "psp reference"],
        amount_labels_pdf=["Gross Credit", "Net Credit", "Amount"],
        fee_labels_pdf=["Commission", "Markup", "Scheme Fees", "Interchange", "Fee"],
        refund_labels_pdf=["Refund", "Gross Debit"],
        chargeback_labels_pdf=["Chargeback"],
        period_labels_pdf=["Booking Date", "Period"],
        amount_columns_tabular=["gross credit", "net credit", "amount", "gross_credit"],
        fee_columns_tabular=["commission", "markup", "scheme fees", "interchange", "fee"],
        refund_columns_tabular=["refund", "gross debit", "gross_debit"],
        chargeback_columns_tabular=["chargeback"],
        date_columns_tabular=["creation date", "booking date", "date"],
        merchant_columns_tabular=["merchant account", "merchant reference"],
    ),
    "Worldpay": ProviderParserProfile(
        provider="Worldpay",
        detection_keywords=["worldpay", "account statement", "access.worldpay.com"],
        amount_labels_pdf=["Credit", "Amount", "Gross"],
        fee_labels_pdf=["Fee", "Commission", "Charges"],
        refund_labels_pdf=["Refund"],
        chargeback_labels_pdf=["Chargeback"],
        period_labels_pdf=["startDate", "endDate", "Period"],
        amount_columns_tabular=["amount", "credit", "gross", "statement amount"],
        fee_columns_tabular=["fee", "fees", "commission", "charges"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargeback amount"],
        date_columns_tabular=["date", "timestamp", "posting date"],
        merchant_columns_tabular=["account number", "party reference", "merchant"],
    ),
    "SumUp": ProviderParserProfile(
        provider="SumUp",
        detection_keywords=["sumup", "sum up", "merchant_code", "payout"],
        amount_labels_pdf=["Amount", "Payout amount", "Transactions"],
        fee_labels_pdf=["Fee", "Fees"],
        refund_labels_pdf=["Refund"],
        chargeback_labels_pdf=["Chargeback"],
        period_labels_pdf=["start_date", "end_date", "Period"],
        amount_columns_tabular=["amount", "payout amount", "gross", "transaction amount"],
        fee_columns_tabular=["fee", "fees"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback"],
        date_columns_tabular=["date", "transaction date", "payout date"],
        merchant_columns_tabular=["merchant_code", "merchant id", "merchant"],
    ),
    "Zettle": ProviderParserProfile(
        provider="Zettle",
        detection_keywords=["zettle", "izettle", "paypal point of sale"],
        amount_labels_pdf=["Amount", "Total sales", "Sales"],
        fee_labels_pdf=["Fee", "Fees"],
        refund_labels_pdf=["Refund"],
        chargeback_labels_pdf=["Chargeback"],
        period_labels_pdf=["Period", "From", "To"],
        amount_columns_tabular=["amount", "sales amount", "total sales"],
        fee_columns_tabular=["fee", "fees"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback"],
        date_columns_tabular=["timestamp", "date", "transaction date"],
        merchant_columns_tabular=["merchant", "store", "account"],
    ),
    "Elavon": ProviderParserProfile(
        provider="Elavon",
        detection_keywords=["elavon"],
        amount_labels_pdf=["Sales", "Transactions", "Gross"],
        fee_labels_pdf=["Fees", "Charges", "Discount Rate"],
        refund_labels_pdf=["Refund"],
        chargeback_labels_pdf=["Chargeback"],
        period_labels_pdf=["Period", "Statement Date"],
        amount_columns_tabular=["sales", "transactions", "gross", "amount"],
        fee_columns_tabular=["fees", "charges", "discount"],
        refund_columns_tabular=["refund", "refunds"],
        chargeback_columns_tabular=["chargeback"],
        date_columns_tabular=["date", "statement date"],
        merchant_columns_tabular=["merchant id", "merchant number", "mid"],
    ),
    "Barclaycard": ProviderParserProfile(
        provider="Barclaycard",
        detection_keywords=["barclaycard", "bcard"],
        amount_labels_pdf=["Card Sales", "Transactions", "Amount"],
        fee_labels_pdf=["Fees", "Service charge"],
        refund_labels_pdf=["Refund"],
        chargeback_labels_pdf=["Chargeback", "Retrieval"],
        period_labels_pdf=["Statement period", "Period"],
        amount_columns_tabular=["card sales", "transactions", "amount", "gross"],
        fee_columns_tabular=["fees", "service charge", "charge"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "retrieval"],
        date_columns_tabular=["date", "statement date", "transaction date"],
        merchant_columns_tabular=["merchant id", "mid", "terminal id"],
    ),
    "Dojo": ProviderParserProfile(
        provider="Dojo",
        detection_keywords=["dojo", "dojo.tech"],
        amount_labels_pdf=["Transactions", "Card Sales", "Amount", "Settled"],
        fee_labels_pdf=["Fees", "Charges", "Processing Fees"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Period", "From", "To"],
        amount_columns_tabular=["amount", "card sales", "transactions", "settled amount", "gross"],
        fee_columns_tabular=["fee", "fees", "charges", "processing fee"],
        refund_columns_tabular=["refund", "refund amount", "refunds"],
        chargeback_columns_tabular=["chargeback", "chargebacks", "reversal"],
        date_columns_tabular=["date", "transaction date", "settlement date", "created"],
        merchant_columns_tabular=["merchant id", "mid", "account", "store"],
    ),
    "Teya": ProviderParserProfile(
        provider="Teya",
        detection_keywords=["teya", "teya solutions"],
        amount_labels_pdf=["Transactions", "Sales", "Gross Amount"],
        fee_labels_pdf=["Fees", "Charges", "Service Fee"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Date", "From", "To"],
        amount_columns_tabular=["amount", "sales", "gross", "transactions"],
        fee_columns_tabular=["fee", "fees", "charge", "charges", "service fee"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "statement date", "transaction date", "settlement date"],
        merchant_columns_tabular=["merchant id", "merchant", "mid", "terminal id"],
    ),
    "Global Payments": ProviderParserProfile(
        provider="Global Payments",
        detection_keywords=["global payments", "globalpay", "merchant portal"],
        amount_labels_pdf=["Transactions", "Sales", "Gross Credit", "Amount"],
        fee_labels_pdf=["Fees", "Charges", "Commission", "Discount Fee"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Period", "From", "To"],
        amount_columns_tabular=["amount", "transactions", "sales", "gross credit", "gross"],
        fee_columns_tabular=["fee", "fees", "charges", "commission", "discount"],
        refund_columns_tabular=["refund", "refund amount", "refunds"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "post date", "settlement date", "transaction date"],
        merchant_columns_tabular=["merchant id", "merchant number", "mid", "account number"],
    ),
    "Trust Payments": ProviderParserProfile(
        provider="Trust Payments",
        detection_keywords=["trust payments", "trustpayments"],
        amount_labels_pdf=["Transactions", "Card Sales", "Amount", "Settlements"],
        fee_labels_pdf=["Fees", "Charges", "Processing Fee", "Commission"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks", "Retrieval"],
        period_labels_pdf=["Period", "From", "To", "Statement Date"],
        amount_columns_tabular=["amount", "transactions", "card sales", "settlement amount", "gross"],
        fee_columns_tabular=["fee", "fees", "charges", "commission", "processing fee"],
        refund_columns_tabular=["refund", "refund amount", "refunds"],
        chargeback_columns_tabular=["chargeback", "chargebacks", "retrieval"],
        date_columns_tabular=["date", "transaction date", "settlement date", "created"],
        merchant_columns_tabular=["merchant id", "merchant", "mid", "site reference"],
    ),
    "Checkout.com": ProviderParserProfile(
        provider="Checkout.com",
        detection_keywords=["checkout.com", "cko", "checkout com"],
        amount_labels_pdf=["Payments", "Amount", "Gross", "Captured"],
        fee_labels_pdf=["Fees", "Fee", "Processing Fee", "Markup"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Dispute", "Chargeback"],
        period_labels_pdf=["Period", "From", "To"],
        amount_columns_tabular=["amount", "gross", "payment amount", "captured amount"],
        fee_columns_tabular=["fee", "fees", "processing fee", "markup"],
        refund_columns_tabular=["refund", "refund amount", "refunds"],
        chargeback_columns_tabular=["chargeback", "dispute"],
        date_columns_tabular=["processed on", "date", "created", "settled on"],
        merchant_columns_tabular=["entity id", "merchant id", "account", "processing channel"],
    ),
    "PaymentSense": ProviderParserProfile(
        provider="PaymentSense",
        detection_keywords=["paymentsense", "payment sense"],
        amount_labels_pdf=["Transactions", "Sales", "Amount", "Card Takings"],
        fee_labels_pdf=["Fees", "Charges", "Service Fee"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Period", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "card takings", "gross"],
        fee_columns_tabular=["fee", "fees", "charge", "charges", "service fee"],
        refund_columns_tabular=["refund", "refunds", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "transaction date", "settlement date"],
        merchant_columns_tabular=["merchant id", "mid", "merchant", "terminal id"],
    ),
    "Takepayments": ProviderParserProfile(
        provider="Takepayments",
        detection_keywords=["takepayments", "take payments"],
        amount_labels_pdf=["Transactions", "Sales", "Amount"],
        fee_labels_pdf=["Fees", "Charges", "Service Fee"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Date", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "gross"],
        fee_columns_tabular=["fee", "fees", "charges", "service fee"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "statement date", "transaction date"],
        merchant_columns_tabular=["merchant id", "mid", "merchant"],
    ),
    "Handepay": ProviderParserProfile(
        provider="Handepay",
        detection_keywords=["handepay"],
        amount_labels_pdf=["Transactions", "Sales", "Amount"],
        fee_labels_pdf=["Fees", "Charges"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Period"],
        amount_columns_tabular=["amount", "sales", "transactions", "gross"],
        fee_columns_tabular=["fee", "fees", "charges"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "transaction date", "statement date"],
        merchant_columns_tabular=["merchant id", "mid", "merchant"],
    ),
    "PayPoint": ProviderParserProfile(
        provider="PayPoint",
        detection_keywords=["paypoint"],
        amount_labels_pdf=["Transactions", "Sales", "Amount", "Settlements"],
        fee_labels_pdf=["Fees", "Charges", "Commission"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "settlement amount"],
        fee_columns_tabular=["fee", "fees", "charges", "commission"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "transaction date", "settlement date"],
        merchant_columns_tabular=["merchant id", "merchant", "mid"],
    ),
    "Payzone": ProviderParserProfile(
        provider="Payzone",
        detection_keywords=["payzone"],
        amount_labels_pdf=["Transactions", "Sales", "Amount"],
        fee_labels_pdf=["Fees", "Charges"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Date"],
        amount_columns_tabular=["amount", "sales", "transactions", "gross"],
        fee_columns_tabular=["fee", "fees", "charges"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "statement date", "transaction date"],
        merchant_columns_tabular=["merchant id", "mid", "merchant"],
    ),
    "myPOS": ProviderParserProfile(
        provider="myPOS",
        detection_keywords=["mypos", "my pos"],
        amount_labels_pdf=["Transactions", "Sales", "Amount", "Settled"],
        fee_labels_pdf=["Fees", "Charges", "Commission"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "settled amount", "gross"],
        fee_columns_tabular=["fee", "fees", "charges", "commission"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "transaction date", "settlement date"],
        merchant_columns_tabular=["merchant id", "account", "mid"],
    ),
    "Moneris": ProviderParserProfile(
        provider="Moneris",
        detection_keywords=["moneris"],
        amount_labels_pdf=["Transactions", "Sales", "Amount", "Gross"],
        fee_labels_pdf=["Fees", "Charges", "Discount"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Date", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "gross"],
        fee_columns_tabular=["fee", "fees", "charges", "discount"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "statement date", "transaction date"],
        merchant_columns_tabular=["merchant id", "merchant number", "mid"],
    ),
    "Valitor": ProviderParserProfile(
        provider="Valitor",
        detection_keywords=["valitor"],
        amount_labels_pdf=["Transactions", "Sales", "Amount"],
        fee_labels_pdf=["Fees", "Charges"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Date"],
        amount_columns_tabular=["amount", "sales", "transactions", "gross"],
        fee_columns_tabular=["fee", "fees", "charges"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "statement date", "transaction date"],
        merchant_columns_tabular=["merchant id", "mid", "merchant"],
    ),
    "Verifone": ProviderParserProfile(
        provider="Verifone",
        detection_keywords=["verifone"],
        amount_labels_pdf=["Transactions", "Sales", "Amount", "Settlement"],
        fee_labels_pdf=["Fees", "Charges", "Processing Fee"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "settlement amount"],
        fee_columns_tabular=["fee", "fees", "charges", "processing fee"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "transaction date", "settlement date"],
        merchant_columns_tabular=["merchant id", "terminal id", "mid"],
    ),
    "Ingenico": ProviderParserProfile(
        provider="Ingenico",
        detection_keywords=["ingenico"],
        amount_labels_pdf=["Transactions", "Sales", "Amount", "Settlement"],
        fee_labels_pdf=["Fees", "Charges"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "settlement amount"],
        fee_columns_tabular=["fee", "fees", "charges"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "transaction date", "settlement date"],
        merchant_columns_tabular=["merchant id", "terminal id", "mid"],
    ),
    "NMI": ProviderParserProfile(
        provider="NMI",
        detection_keywords=["nmi"],
        amount_labels_pdf=["Transactions", "Sales", "Amount"],
        fee_labels_pdf=["Fees", "Charges"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "gross"],
        fee_columns_tabular=["fee", "fees", "charges"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "transaction date", "settlement date"],
        merchant_columns_tabular=["merchant id", "mid", "merchant"],
    ),
    "EVO Payments": ProviderParserProfile(
        provider="EVO Payments",
        detection_keywords=["evo", "evo payments"],
        amount_labels_pdf=["Transactions", "Sales", "Amount", "Gross"],
        fee_labels_pdf=["Fees", "Charges", "Discount Fee"],
        refund_labels_pdf=["Refund", "Refunds"],
        chargeback_labels_pdf=["Chargeback", "Chargebacks"],
        period_labels_pdf=["Period", "Statement Date", "From", "To"],
        amount_columns_tabular=["amount", "sales", "transactions", "gross"],
        fee_columns_tabular=["fee", "fees", "charges", "discount"],
        refund_columns_tabular=["refund", "refund amount"],
        chargeback_columns_tabular=["chargeback", "chargebacks"],
        date_columns_tabular=["date", "statement date", "transaction date"],
        merchant_columns_tabular=["merchant id", "merchant number", "mid"],
    ),
}


def get_provider_profile(provider_name: Optional[str]) -> Optional[ProviderParserProfile]:
    if not provider_name:
        return None
    return PROVIDER_PARSER_PROFILES.get(provider_name)


def providers_with_native_profiles() -> List[str]:
    """Providers with dedicated parsing (tabular profile and/or hardcoded PDF path in ingestion)."""
    extra_pdf_native = {"PayPal", "Zempler", "DNA Payments", "Shopify Payments"}
    return sorted(set(PROVIDER_PARSER_PROFILES.keys()) | extra_pdf_native)

