# app/config/industry_config.py
"""Industry-specific configuration and thresholds for financial analysis."""

# Industry thresholds for financial metrics
INDUSTRY_THRESHOLDS = dict(sorted({
    'Medical Practices (GPs, Clinics, Dentists)': {
        'Debt Service Coverage Ratio': 1.60,
        'Net Income': 1000,
        'Operating Margin': 0.10,
        'Revenue Growth Rate': 0.06,
        'Cash Flow Volatility': 0.08,
        'Gross Burn Rate': 16000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 900,
        'Average Negative Balance Days per Month': 0,
        'Number of Bounced Payments': 0,
    },
    'Pharmacies (Independent or Small Chains)': {
        'Debt Service Coverage Ratio': 1.60,
        'Net Income': 500,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.08,
        'Gross Burn Rate': 15000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 750,
        'Average Negative Balance Days per Month': 0,
        'Number of Bounced Payments': 0,
    },
    'Business Consultants': {
        'Debt Service Coverage Ratio': 1.60,
        'Net Income': 1000,
        'Operating Margin': 0.09,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.08,
        'Gross Burn Rate': 14000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 750,
        'Average Negative Balance Days per Month': 0,
        'Number of Bounced Payments': 0,
    },
    'IT Services and Support Companies': {
        'Debt Service Coverage Ratio': 1.55,
        'Net Income': 500,
        'Operating Margin': 0.12,
        'Revenue Growth Rate': 0.07,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 13000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 0,
        'Number of Bounced Payments': 0,
    },
    'Courier Services (Independent and Regional Operators)': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 500,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.06,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 12000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 0,
        'Number of Bounced Payments': 0,
    },
    'Grocery Stores and Mini-Markets': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 500,
        'Operating Margin': 0.07,
        'Revenue Growth Rate': 0.06,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 10000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Education': {
        'Debt Service Coverage Ratio': 1.45,
        'Net Income': 1500,
        'Operating Margin': 0.10,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.09,
        'Gross Burn Rate': 11500,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Engineering': {
        'Debt Service Coverage Ratio': 1.55,
        'Net Income': 7000,
        'Operating Margin': 0.07,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 13000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 650,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Estate Agent': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 4500,
        'Operating Margin': 0.09,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 13000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 650,
        'Average Negative Balance Days per Month': 0,
        'Number of Bounced Payments': 0,
    },
    'Food Service': {
        'Debt Service Coverage Ratio': 1.55,
        'Net Income': 2500,
        'Operating Margin': 0.06,
        'Revenue Growth Rate': 0.06,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 11000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Import / Export': {
        'Debt Service Coverage Ratio': 1.55,
        'Net Income': 3000,
        'Operating Margin': 0.07,
        'Revenue Growth Rate': 0.06,
        'Cash Flow Volatility': 0.15,
        'Gross Burn Rate': 11000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Manufacturing': {
        'Debt Service Coverage Ratio': 1.60,
        'Net Income': 1500,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.11,
        'Gross Burn Rate': 13500,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 750,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Marketing / Advertising / Design': {
        'Debt Service Coverage Ratio': 1.55,
        'Net Income': 5000,
        'Operating Margin': 0.11,
        'Revenue Growth Rate': 0.06,
        'Cash Flow Volatility': 0.11,
        'Gross Burn Rate': 13500,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 750,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Off-Licence Business': {
        'Debt Service Coverage Ratio': 1.55,
        'Net Income': 4500,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.06,
        'Cash Flow Volatility': 0.11,
        'Gross Burn Rate': 14000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 650,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Other': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 3000,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.13,
        'Gross Burn Rate': 11000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Personal Services': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 2000,
        'Operating Margin': 0.09,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 12000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Restaurants and Cafes': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 0,
        'Operating Margin': 0.05,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.16,
        'Gross Burn Rate': 11000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Bars and Pubs': {
        'Debt Service Coverage Ratio': 1.25,
        'Net Income': 0,
        'Operating Margin': 0.04,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.18,
        'Gross Burn Rate': 10000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Beauty Salons and Spas': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 500,
        'Operating Margin': 0.06,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.14,
        'Gross Burn Rate': 9500,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 550,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'E-Commerce Retailers': {
        'Debt Service Coverage Ratio': 1.35,
        'Net Income': 1000,
        'Operating Margin': 0.07,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.14,
        'Gross Burn Rate': 10000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Event Planning and Management Firms': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 500,
        'Operating Margin': 0.05,
        'Revenue Growth Rate': 0.03,
        'Cash Flow Volatility': 0.16,
        'Gross Burn Rate': 10000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Auto Repair Shops': {
        'Debt Service Coverage Ratio': 1.40,
        'Net Income': 1000,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 9500,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 650,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Fitness Centres and Gyms': {
        'Debt Service Coverage Ratio': 1.35,
        'Net Income': 500,
        'Operating Margin': 0.06,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.18,
        'Gross Burn Rate': 10000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Construction Firms': {
        'Debt Service Coverage Ratio': 1.30,
        'Net Income': 1000,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.16,
        'Gross Burn Rate': 12500,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Printing / Publishing': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 2500,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.14,
        'Gross Burn Rate': 11000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 650,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Recruitment': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 2000,
        'Operating Margin': 0.09,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.10,
        'Gross Burn Rate': 13000,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 600,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Retail': {
        'Debt Service Coverage Ratio': 1.40,
        'Net Income': 2500,
        'Operating Margin': 0.09,
        'Revenue Growth Rate': 0.04,
        'Cash Flow Volatility': 0.14,
        'Gross Burn Rate': 11500,
        'Directors Score': 75,
        'Sector Risk': 1,
        'Average Month-End Balance': 620,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Telecommunications': {
        'Debt Service Coverage Ratio': 1.55,
        'Net Income': 5000,
        'Operating Margin': 0.11,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.12,
        'Gross Burn Rate': 13000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
    'Tradesman': {
        'Debt Service Coverage Ratio': 1.40,
        'Net Income': 4000,
        'Operating Margin': 0.08,
        'Revenue Growth Rate': 0.05,
        'Cash Flow Volatility': 0.15,
        'Gross Burn Rate': 11500,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 2,
        'Number of Bounced Payments': 0,
    },
    'Wholesaler / Distributor': {
        'Debt Service Coverage Ratio': 1.50,
        'Net Income': 3500,
        'Operating Margin': 0.10,
        'Revenue Growth Rate': 0.06,
        'Cash Flow Volatility': 0.13,
        'Gross Burn Rate': 13000,
        'Directors Score': 75,
        'Sector Risk': 0,
        'Average Month-End Balance': 700,
        'Average Negative Balance Days per Month': 1,
        'Number of Bounced Payments': 0,
    },
}.items()))

# Industry risk classifications
LOW_RISK_SECTORS = [
    'Medical Practices (GPs, Clinics, Dentists)',
    'Pharmacies (Independent or Small Chains)',
    'Business Consultants',
    'IT Services and Support Companies',
    'Courier Services (Independent and Regional Operators)',
    'Grocery Stores and Mini-Markets',
    'Education',
    'Engineering',
    'Estate Agent',
    'Telecommunications',
]

HIGH_RISK_SECTORS = [
    'Restaurants and Cafes',
    'Bars and Pubs',
    'Event Planning and Management Firms',
    'Construction Firms',
    'Beauty Salons and Spas',
]

MODERATE_RISK_SECTORS = [
    'Manufacturing',
    'Retail',
    'Food Service',
    'Tradesman',
    'Import / Export',
    'Marketing / Advertising / Design',
    'Off-Licence Business',
    'Wholesaler / Distributor',
    'Auto Repair Shops',
    'Printing / Publishing',
    'Recruitment',
    'Personal Services',
    'E-Commerce Retailers',
    'Fitness Centres and Gyms',
    'Other',
]